version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: django-web
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: changeme
      DJANGO_ALLOWED_HOSTS: 0.0.0.0
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    container_name: django-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
